# Site settings
title: Amanda Falke, Software Engineer
tagline: "Embedded Systems and Web Development"
author: Amanda Falke
email: abstractmachines@gmail.com
description: "Hi, I'm Amanda, a software engineer currently located in Portland
 Oregon."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://github.com/abstractmachines" # the base hostname & protocol for your site
twitter_username: amanda_machina
github_username:  abstractmachines

portfolio_url: "http://abstractmachines.net"
portfolio_text: "abstractmachines.net"

# Google Analytics

# Build settings
timezone: Pacific
permalink: /post/:title/

theme: jekyll-theme-tactile
